# Generated by Django 3.1.2 on 2020-10-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
